# See https://pre-commit.com for more information
repos:
  # Standard hooks for code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Ruff - Fast Python linter (handles imports too)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # Black - The uncompromising Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  # Prettier - Format non-Python files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [markdown, json, yaml, toml]
        exclude: ^(.*\.py|.*\.ipynb)$
